version: "1"
rules:
  - base: main
    upstream: KelvinTegelaar:main
    mergeMethod: hardreset
  - base: dev
    upstream: KelvinTegelaar:dev
    mergeMethod: hardreset
  - base: website
    upstream: KelvinTegelaar:website
    mergeMethod: hardreset
