---
# Configuration file for MegaLinter
# See all available variables at https://megalinter.github.io/configuration/ and in linters documentation
APPLY_FIXES: none
SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false
ENABLE: [CSS, HTML, JSON, YAML, JSX, ACTION, CREDENTIALS]
DISABLE_LINTERS: [CSS_SCSS_LINT, YAML_PRETTIER]
SHOW_SKIPPED_LINTERS: false
