blank_issues_enabled: false
contact_links:
  - name: Security Reports
    url: https://github.com/KelvinTegelaar/CIPP/security/advisories
    about: Please report security vulnerabilities here.
  - name: Community Discord
    url: https://discord.gg/cyberdrain
    about: Join our discord community here.
    
