name: CIPP Frontend Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    if: github.event.repository.fork == false
    name: Build and Upload CIPP Frontend
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4.2.2

      # Set up Node.js
      - name: Get Node version
        id: get_node_version
        run: |
          node_raw_version=$(node -p "require('./package.json').engines.node")
          node_sanitized_version=$(echo $node_raw_version | sed -E 's/[^0-9.]+//g')
          echo "node_version=$node_sanitized_version" >> $GITHUB_OUTPUT

      - name: Set up Node.js
        uses: actions/setup-node@v4.2.0
        with:
          node-version: ${{ steps.get_node_version.outputs.node_version }}

      # Install dependencies
      - name: Install Dependencies
        run: yarn install

      # Build the project
      - name: Build Project
        run: npm run build

      # Create ZIP File in a New Source Directory
      - name: Prepare and Zip Build Files
        run: |
          mkdir -p build
          cp staticwebapp.config.json out/
          zip -r build/latest.zip out

      # Upload to Azure Blob Storage
      - name: Azure Blob Upload
        uses: LanceMcCarthy/Action-AzureBlobUpload@v3.3.1
        with:
          connection_string: ${{ secrets.AZURE_CONNECTION_STRING }}
          container_name: cipp
          source_folder: build/
          destination_folder: /
          delete_if_exists: true
