---
name: Label Issues
on:  # yamllint disable-line rule:truthy
  issues:
    types:
      - opened
jobs:
  label_issues_bugs:
    if: contains(github.event.issue.title,'Bug')
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Sponsor Labels
        uses: JasonEtco/is-sponsor-label-action@v1.2.0
        with:
         label: 'Sponsor Request'
